import type { CfoData, CfoReportRow } from "@/types/cash";
import { ConfidencePill } from "@/components/ui/Badge";
import { ActionsRequiredSection } from "./ActionsRequiredSection";

function ReportRow({ row }: { row: CfoReportRow }) {
  return (
    <div
      className={`flex items-center justify-between px-2 py-1.5 text-[12px] ${
        row.flagged ? "rounded-[5px] bg-amber-light font-semibold text-amber" : "text-text-2"
      }`}
    >
      <span>{row.label}</span>
      <span className="font-data text-text-1">{row.value}</span>
    </div>
  );
}

export function CfoReport({ data }: { data: CfoData }) {
  const { sections } = data;

  return (
    <div className="rounded-md border border-border-0 bg-bg-surface shadow-[var(--shadow-card)] print:border-0 print:shadow-none">
      {/* Cover */}
      <div className="rounded-t-md bg-blue p-6 text-white">
        <div className="flex items-start justify-between">
          <div>
            <div className="mb-2 text-[11px] uppercase tracking-widest text-white/60">
              Core Fintech · Core Cash Agent
            </div>
            <div className="text-2xl font-bold">Daily Cash &amp; Liquidity Report</div>
            <div className="mt-1 font-data text-[11px] text-white/70">
              {data.reportDate} · FORECAST VERSION {data.forecastVersion} · AGENT RUN {data.agentRunTime}
            </div>
          </div>
          <ConfidencePill level={data.confidence} />
        </div>
        <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">
          {data.coverStats.map((stat) => (
            <div key={stat.label} className="rounded-md bg-white/10 px-3 py-2">
              <div className="text-[10px] uppercase tracking-wide text-white/60">{stat.label}</div>
              <div className="font-data text-[14px] font-bold">{stat.value}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Report body */}
      <div className="flex flex-col gap-5 p-5">
        <Section number={1} title="Executive Summary">
          <p className="text-[12.5px] leading-relaxed text-text-2">{sections.executiveSummary}</p>
        </Section>

        <Section number={2} title="Cash Position">
          <div className="flex flex-col">
            {sections.cashPosition.map((row) => (
              <ReportRow key={row.label} row={row} />
            ))}
          </div>
        </Section>

        <Section number={3} title="Forecast Outlook">
          <div className="flex flex-col">
            {sections.forecastOutlook.map((row) => (
              <ReportRow key={row.label} row={row} />
            ))}
          </div>
        </Section>

        <Section number={4} title="Actions Required">
          <ActionsRequiredSection actions={sections.actionsRequired} />
        </Section>

        <Section number={5} title={`Variance Explanation — ${sections.varianceExplanation.windowLabel}`}>
          <p className="text-[12.5px] leading-relaxed text-text-2">{sections.varianceExplanation.text}</p>
        </Section>

        <Section number={6} title="Data Caveats">
          <p className="text-[12.5px] leading-relaxed text-text-2">{sections.dataCaveats}</p>
        </Section>

        <Section number={7} title="Source References">
          <div className="grid grid-cols-1 gap-x-6 gap-y-1 sm:grid-cols-2">
            {sections.sourceReferences.map((ref) => (
              <div key={ref.label} className="flex items-center justify-between px-2 py-1 text-[12px]">
                <span className="text-text-2">{ref.label}</span>
                <span className="font-data text-[11px] text-text-muted">{ref.detail}</span>
              </div>
            ))}
          </div>
        </Section>

        <div className="border-t border-border-0 pt-3 text-center text-[10.5px] leading-relaxed text-text-muted">
          Generated by Core Cash Agent (Agent 5) · All recommendations require human approval · Core Fintech ·
          Internal &amp; Confidential · {data.reportDate}
        </div>
      </div>
    </div>
  );
}

function Section({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="mb-2 text-[13px] font-bold text-text-1">
        {number} · {title}
      </div>
      {children}
    </div>
  );
}
