import type { ForecastData } from "@/types/cash";

// Hardcoded mock data shaped like the future FastAPI response.
// Numbers sourced from design-reference/core-cash-agent-full.html.
export const mockForecastData: ForecastData = {
  version: "v4",
  asOf: "26 Jun 2026 · 09:14",
  openingCash: 12_840_000,
  expectedInflows: 2_400_000,
  expectedOutflows: 6_140_000,
  lowPointWarning:
    "Lowest point: $4.1M in week 2 (7–11 Jul) — payroll $780K + Q2 tax $280K + delayed AR $340K. Recommend GBP→USD transfer before Thu 2 Jul cut-off.",
  horizons: [
    { horizon: 7, closingBalance: 9_100_000, trend: "improving", trendLabel: "Improving" },
    { horizon: 30, closingBalance: 6_200_000, trend: "watch", trendLabel: "Watch payroll" },
    { horizon: 60, closingBalance: 7_800_000, trend: "stable", trendLabel: "Stable" },
  ],
  series: {
    7: [
      { label: "Mon", date: "22 Jun", balance: 12_840_000 },
      { label: "Tue", date: "23 Jun", balance: 12_400_000 },
      { label: "Wed", date: "24 Jun", balance: 11_900_000 },
      { label: "Thu", date: "25 Jun", balance: 11_200_000 },
      { label: "Fri", date: "26 Jun", balance: 10_400_000 },
      { label: "Sat", date: "27 Jun", balance: 9_800_000 },
      { label: "Sun", date: "28 Jun", balance: 9_100_000 },
    ],
    30: [
      { label: "Wk1", date: "29 Jun", balance: 11_600_000 },
      { label: "Wk2", date: "6 Jul", balance: 4_100_000 },
      { label: "Wk3", date: "13 Jul", balance: 5_400_000 },
      { label: "Wk4", date: "20 Jul", balance: 6_200_000 },
    ],
    60: [
      { label: "Mo1", date: "Jul", balance: 6_200_000 },
      { label: "Mo2", date: "Aug", balance: 7_800_000 },
    ],
  },
  entityRows: [
    {
      entity: "US HQ",
      currency: "USD",
      opening: 8_640_000,
      inflows: 1_200_000,
      outflows: 4_800_000,
      closing: 5_040_000,
      confidence: "high",
      note: "Payroll + tax wk2",
    },
    {
      entity: "UK Operations",
      currency: "GBP",
      opening: 3_120_000,
      inflows: 800_000,
      outflows: 620_000,
      closing: 3_300_000,
      confidence: "medium",
      note: "Barclays stale",
    },
    {
      entity: "EU Entity",
      currency: "EUR",
      opening: 430_000,
      inflows: 0,
      outflows: 120_000,
      closing: 310_000,
      confidence: "medium",
      note: "Funding required",
      warning: true,
    },
  ],
  assumptions: [
    {
      id: "assume-1",
      entity: "US HQ",
      type: "outflow",
      amount: 780_000,
      currency: "USD",
      description: "Payroll — 4 Jul 2026",
      date: "2026-07-04",
      category: "Payroll",
      confidence: "high",
    },
    {
      id: "assume-2",
      entity: "US HQ",
      type: "outflow",
      amount: 280_000,
      currency: "USD",
      description: "Q2 Tax Reserve — 5 Jul 2026",
      date: "2026-07-05",
      category: "Tax",
      confidence: "high",
    },
    {
      id: "assume-3",
      entity: "UK Operations",
      type: "inflow",
      amount: 340_000,
      currency: "GBP",
      description: "Customer A delayed receipt — 7 Jul 2026",
      date: "2026-07-07",
      category: "AR",
      confidence: "medium",
    },
    {
      id: "assume-4",
      entity: "EU Entity",
      type: "outflow",
      amount: 120_000,
      currency: "EUR",
      description: "Vendor AP — 28 Jun 2026",
      date: "2026-06-28",
      category: "AP",
      confidence: "high",
    },
  ],
  varianceWindowLabel: "19–25 Jun 2026",
  totalVariance: -340_000,
  inflowVariance: -480_000,
  outflowVariance: 140_000,
  explainedDriverCount: 4,
  varianceDrivers: [
    {
      id: "drv-1",
      label: "Delayed Collection",
      amount: -340_000,
      pctOfMax: 70,
      confidence: "high",
      note: "Customer A delayed 5d",
      favorable: false,
    },
    {
      id: "drv-2",
      label: "Early AP Payment",
      amount: 140_000,
      pctOfMax: 30,
      confidence: "high",
      note: "Vendor B settled early",
      favorable: true,
    },
    {
      id: "drv-3",
      label: "AR Timing Diff.",
      amount: -140_000,
      pctOfMax: 40,
      confidence: "medium",
      note: "±3 day tolerance",
      favorable: false,
    },
    {
      id: "drv-4",
      label: "Bank Fees",
      amount: -2_000,
      pctOfMax: 5,
      confidence: "high",
      note: "SWIFT fees not modelled",
      favorable: false,
    },
  ],
};
