import type { DashboardData } from "@/types/cash";

// Hardcoded mock data shaped like the future FastAPI response.
// Numbers sourced from design-reference/core-cash-agent-full.html.
export const mockDashboardData: DashboardData = {
  asOf: "26 Jun 2026 · 09:14",
  totalCashUsd: 12_840_000,
  totalCashDeltaPct: 2.7,
  usableCashUsd: 9_440_000,
  restrictedCashUsd: 3_400_000,
  dataConfidence: "high",
  liquidityStatus: "normal",
  liquidityHeadline:
    "You have 47 days of cash at current burn rate. No shortfalls in 7-day window. GBP pool has £2.1M surplus available for deployment.",
  cashRunwayDays: 47,
  cashRunwayDeltaDays: 2,
  sevenDayForecastUsd: 9_100_000,
  openExceptionsCount: 3,
  currencyBreakdown: [
    { currency: "USD", amount: 8_640_000, pctOfTotal: 67.3, belowThreshold: false },
    { currency: "GBP", amount: 3_120_000, pctOfTotal: 24.3, belowThreshold: false },
    { currency: "EUR", amount: 430_000, pctOfTotal: 8.0, belowThreshold: true },
  ],
  entityGroups: [
    {
      entity: "US HQ",
      currency: "USD",
      totalBalance: 8_640_000,
      accounts: [
        {
          id: "jpm-usd-main",
          name: "JPM USD Main",
          maskedNumber: "****4821",
          bank: "JPMorgan",
          entity: "US HQ",
          currency: "USD",
          balance: 5_240_000,
          usableBalance: 5_240_000,
          minThreshold: 500_000,
          confidence: "high",
          restricted: false,
          sourceLabel: "BAI2 · 09:02",
        },
        {
          id: "jpm-usd-payroll",
          name: "JPM USD Payroll",
          maskedNumber: "****4830",
          bank: "JPMorgan",
          entity: "US HQ",
          currency: "USD",
          balance: 2_000_000,
          usableBalance: 2_000_000,
          minThreshold: 1_800_000,
          confidence: "high",
          restricted: false,
          sourceLabel: "BAI2 · 09:02",
        },
        {
          id: "citi-usd-restricted",
          name: "Citi USD Restricted",
          maskedNumber: "****9901",
          bank: "Citibank",
          entity: "US HQ",
          currency: "USD",
          balance: 1_400_000,
          usableBalance: 0,
          minThreshold: null,
          confidence: "high",
          restricted: true,
          flag: "Restricted",
          sourceLabel: "BAI2 · 09:02",
        },
      ],
    },
    {
      entity: "UK Operations",
      currency: "GBP",
      totalBalance: 3_120_000,
      accounts: [
        {
          id: "hsbc-gbp-pool",
          name: "HSBC GBP Pool",
          maskedNumber: "****0033",
          bank: "HSBC",
          entity: "UK Operations",
          currency: "GBP",
          balance: 2_800_000,
          usableBalance: 2_800_000,
          minThreshold: 700_000,
          confidence: "high",
          restricted: false,
          sourceLabel: "camt.053 · 08:55",
        },
        {
          id: "barclays-gbp-ops",
          name: "Barclays GBP Ops",
          maskedNumber: "****1122",
          bank: "Barclays",
          entity: "UK Operations",
          currency: "GBP",
          balance: 320_000,
          usableBalance: 320_000,
          minThreshold: 200_000,
          confidence: "medium",
          restricted: false,
          flag: "Stale 2d",
          sourceLabel: "MT940 · 24 Jun",
        },
      ],
    },
    {
      entity: "EU Entity",
      currency: "EUR",
      totalBalance: 430_000,
      accounts: [
        {
          id: "bofa-eur-reserve",
          name: "BofA EUR Reserve",
          maskedNumber: "****7712",
          bank: "Bank of America",
          entity: "EU Entity",
          currency: "EUR",
          balance: 430_000,
          usableBalance: 0,
          minThreshold: 500_000,
          confidence: "medium",
          restricted: false,
          flag: "Below min",
          sourceLabel: "camt.053 · 09:01",
        },
        {
          id: "bofa-eur-ops",
          name: "BofA EUR Ops",
          maskedNumber: "****7730",
          bank: "Bank of America",
          entity: "EU Entity",
          currency: "EUR",
          balance: 0,
          usableBalance: 0,
          minThreshold: 100_000,
          confidence: "high",
          restricted: false,
          flag: "Zero balance",
          sourceLabel: "camt.053 · 09:01",
        },
      ],
    },
  ],
  recommendation: {
    id: "rec-eu-eur-funding",
    agentLabel: "Agent 3 · Liquidity Risk",
    confidence: "high",
    body: "Review funding for EU Entity BofA EUR Reserve (****7712). Balance €430K is below minimum of €500K. Consider transferring EUR 150,000 from HSBC GBP Pool or intercompany facility before end of business today.",
    why: "BofA EUR Reserve €70K below minimum · EU AP €120K due Fri 28 Jun · No EUR AR before 2 Jul · GBP pool £2.1M above minimum",
    approvalOwner: "Finance Director",
    cutoff: "15:00 CET",
    generatedAt: "09:14 UTC",
  },
  exceptions: [
    {
      id: "exc-1",
      severity: "error",
      title: "BofA EUR Reserve — Below Minimum",
      description: "€430K vs €500K threshold. EU AP due Fri 28 Jun.",
    },
    {
      id: "exc-2",
      severity: "warning",
      title: "Barclays GBP — Stale 2 days",
      description: "Statement not received since 24 Jun. UK Ops confidence reduced.",
    },
    {
      id: "exc-3",
      severity: "warning",
      title: "AR — 3 Unmapped Counterparties",
      description: "3 AR lines (~$140K) not matched to entity master.",
    },
  ],
  riskScore: 2,
  riskScoreDelta: "▲ Improved from 3",
  activeBreaches: 1,
  activeBreachesLabel: "BofA EUR Reserve",
  concentrationRiskLevel: "Low",
  concentrationRiskSub: "USD 67% · GBP 24%",
  riskItems: [
    {
      id: "risk-1",
      severity: "critical",
      title: "BofA EUR Reserve — Below Minimum Threshold",
      description:
        "Balance €430K is €70K below the €500K minimum. EU AP of €120K due Fri 28 Jun will reduce to €310K. Funding required before 15:00 CET today.",
      owner: "Finance Director",
    },
    {
      id: "risk-2",
      severity: "watch",
      title: "Barclays GBP Ops — Stale Balance (2 days)",
      description:
        "Statement not received since 24 Jun. Balance confidence reduced to Medium. UK Operations forecast may be understated.",
    },
    {
      id: "risk-3",
      severity: "watch",
      title: "EUR Concentration Risk — Sub-Threshold",
      description:
        "EUR position 3.3% of total cash, below the 5% minimum currency policy. No EUR AR expected before 2 Jul.",
    },
  ],
  thresholdMonitoring: [
    { accountName: "JPM USD Main", pctOfThreshold: 91, displayBalance: "$5.24M", status: "ok" },
    { accountName: "JPM USD Payroll", pctOfThreshold: 95, displayBalance: "$2.00M", status: "ok" },
    { accountName: "HSBC GBP Pool", pctOfThreshold: 80, displayBalance: "£2.80M", status: "ok" },
    { accountName: "BofA EUR Reserve", pctOfThreshold: 14, displayBalance: "€430K", status: "low" },
  ],
};
